# Generated by Django 5.2.7 on 2025-10-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('validade', models.DateField(verbose_name='Validade do Contrato')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.sistema', verbose_name='Sistema')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.tecnico', verbose_name='Técnico')),
            ],
            options={
                'ordering': ['empresa'],
            },
        ),
    ]
