# Generated by Django 5.2.7 on 2025-10-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pdf_anexo',
            field=models.FileField(blank=True, null=True, upload_to='contratos_pdfs/', verbose_name='Anexo PDF'),
        ),
    ]
