# Generated by Django 5.2.7 on 2025-10-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_cliente_descricao_cliente_pdf_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='meses_contrato',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cobranca',
            field=models.CharField(blank=True, choices=[('M', 'Mensal'), ('A', 'Anual')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
