# Generated by Django 5.2.7 on 2025-10-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_cliente_meses_contrato_cliente_tipo_cobranca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
    ]
