# Generated by Django 5.2.7 on 2025-10-14 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_alter_cliente_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
    ]
