# Generated by Django 5.2.7 on 2025-10-16 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_cliente_data_criacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoRenovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_renovacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Renovação')),
                ('validade_anterior', models.DateField(verbose_name='Validade Anterior')),
                ('nova_validade', models.DateField(verbose_name='Nova Validade')),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Anterior')),
                ('porcentagem_reajuste', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Reajuste Aplicado (%)')),
                ('novo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Novo Valor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_renovacoes', to='contratos.cliente')),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Renovação',
                'verbose_name_plural': 'Históricos de Renovações',
                'ordering': ['-data_renovacao'],
            },
        ),
    ]
