# Generated by Django 5.2.7 on 2025-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_historicorenovacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
    ]
