# Generated by Django 5.2.7 on 2025-10-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_historicorenovacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Anexo')),
                ('arquivo', models.FileField(upload_to='anexos_clientes/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='contratos.cliente')),
            ],
            options={
                'verbose_name': 'Anexo de Cliente',
                'verbose_name_plural': 'Anexos de Clientes',
                'ordering': ['-data_upload'],
            },
        ),
    ]
