# Generated by Django 5.2.7 on 2025-10-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_anexocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexocliente',
            name='descricao',
        ),
    ]
