# Generated by Django 5.2 on 2025-09-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_transacao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.IntegerField(choices=[(0, 'Ativo'), (1, 'Inativo')], default=0),
        ),
    ]
