# Generated by Django 5.2.6 on 2025-09-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_produto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='alerta_estoque_minimo',
            field=models.PositiveIntegerField(blank=True, help_text='Receber um alerta quando o estoque atingir esta quantidade. Deixe em branco para não avisar.', null=True, verbose_name='Quantidade para Aviso'),
        ),
    ]
