# Generated by Django 5.2.6 on 2025-09-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_produto_alerta_estoque_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='arquivada',
            field=models.BooleanField(default=False),
        ),
    ]
