# Generated by Django 5.2.7 on 2025-10-29 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome/Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.categoriapedido', verbose_name='Categoria Padrão')),
            ],
            options={
                'verbose_name': 'Cliente (Pedido)',
                'verbose_name_plural': 'Clientes (Pedido)',
                'ordering': ['nome'],
            },
        ),
    ]
