# Generated by Django 5.2.7 on 2025-10-29 13:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_clientepedido_cep_clientepedido_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepedido',
            name='valor_pedido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor do Pedido'),
        ),
        migrations.AlterField(
            model_name='clientepedido',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pedido.categoriapedido', verbose_name='Categoria do Pedido'),
        ),
        migrations.AlterField(
            model_name='clientepedido',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ/CPF'),
        ),
    ]
