# Generated by Django 5.2.7 on 2025-10-29 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_alter_cliente_cnpj'),
        ('pedido', '0004_clientepedido_valor_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepedido',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.tecnico', verbose_name='Técnico Responsável'),
        ),
    ]
