# Generated by Django 5.2.7 on 2025-10-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_clientepedido_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepedido',
            name='descricao_pedido',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Pedido'),
        ),
    ]
