# Generated by Django 5.2.7 on 2025-10-29 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_clientepedido_usuario_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
    ]
